+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+      /\                                                               +
+     /  \       MIOS is distributed with ABSOLUTELY NO WARRANTY.       +
+    /    \           A Busybox & Fltk minimal desktop.                 +
+   /  MI  \             https://starboot.cn                            +
+  /--------\                                                           +
+                             Version 1.0                               +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Welcome to MIOS. This is a collection of extensions
to help get started with MIOS Linux. It is not intended to be a 
replacement for distribution.

Booting from this CD will first load your regular extensions (if any),
then load the additional extensions for installation, networking, and 
remastering.

Press <Enter> for MIOS 
Or Press F2, F3, or F4 to view additional boot options, F1 returns here.
